version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: prv
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: prv_system
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql